baseURL: https://pytorch-ignite.ai
languageCode: en-us
title: PyTorch-Ignite
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description: High-level library to help with training and evaluating neural networks in PyTorch flexibly and transparently.
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/ignite_logomark.svg
    link: /
  font:
    name: "Oxygen"
    sizes: [400,600]
  hero:
    # Main hero title
    title: PyTorch-Ignite
    # Hero subtitle (optional)
    subtitle: High-level library to help with training and evaluating neural networks in PyTorch flexibly and transparently.
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from static/images/___)
    image: logos/ignite_logo.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    # clientlogos:
    # - systek
    # - tribe
    # - kromo
    # - infinite
    # - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Documentation
    url: https://pytorch.org/ignite
  - title: GitHub
    url: https://github.com/pytorch/ignite
  - title: Blog
    url: /blog
    # sublinks:
    # - title: Dropdown item
    #   url: /
    # - title: Dropdown item
    #   url: /
    # - title: Dropdown item
    #   url: /
  - title: Community
    url: /community
  # - title: Sign up
  #   url: /
  #   button: true
  # sidebar:
    # Logo (from /images/logos/___.svg)
    # logo: fresh-square
    # sections:
    # - title: User
    #   icon: user
    #   links:
    #   - text: Profile
    #     url: /
    #   - text: Account
    #     url: /
    #   - text: Settings
    #     url: /
    # - title: Messages
    #   icon: envelope
    #   links:
    #   - text: Inbox
    #     url: /
    #   - text: Compose
    #     url: /
    # - title: Images
    #   icon: image
    #   links:
    #   - text: Library
    #     url: /
    #   - text: Upload
    #     url: /
    # - title: Settings
    #   icon: cog
    #   links:
    #   - text: User settings
    #     url: /
    #   - text: App settings
    #     url: /
  section1:
    title: Places Ignite shines
    # subtitle: with great responsibility
    tiles:
    - title: Simplicity
      icon: mouse-globe
      text: Extremely simple engine and event system
      url: /
      buttonText: Learn More
    - title: Rich metrics
      icon: laptop-cloud
      text: Out-of-the-box metrics to easily evaluate models
      url: /
      buttonText: Learn More
    - title: Unparalleled flexibility of Handlers
      icon: plug-cloud
      text: Built-in handlers to compose training pipeline, save artifacts and log parameters and metrics
      url: /
      buttonText: Learn More
  section2:
    title: E C O S Y S T E M
    subtitle: And we know it
    features:
    - title: Project MONAI
      text: MONAI is a PyTorch-based, open-source framework for deep learning in healthcare imaging, part of PyTorch Ecosystem.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: DeepSeismic
      text: Deep Learning for Seismic Imaging and Interpretation
      icon: doc-sync
    - title: Nussl
      text: A flexible source separation library in Python
      icon: mobile-feed
  # section3:
  #   title: One platform
  #   subtitle: To rule them all
  #   image: illustrations/mockups/app-mockup.png
  #   buttonText: Get started
  #   buttonLink: "#"
  # section4:
  #   title: Our Clients love us!
  #   subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
  #   clients:
  #   - name: Irma Walters
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: Accountant
  #     img: 1
  #   - name: John Bradley
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: Financial Analyst
  #     img: 2
  #   - name: Gary Blackman
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: HR Manager
  #     img: 3
  # section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: ignite_logomark.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/pytorch/ignite
      # Icons are from Font Awesome
      icon: github
    - link: https://facebook.com/pytorch-ignite
      icon: facebook
    - link: https://twitter.com/pytorch_ignite
      icon: twitter
    quicklinks:
      column1:
        title: "Product"
        links:
        - text: Discover features
          link: /
        - text: Why choose our product?
          link: /
        - text: Compare features
          link: /
        - text: Our roadmap
          link: /
        - text: AGB
          link: /agb
      column2:
        title: "Docs"
        links:
        - text: Get started
          link: /
        - text: User guides
          link: /
        - text: Admin guide
          link: /
        - text: Developers
          link: /
      column3:
        title: "Blog"
        links:
        - text: Latest news
          link: /blog/first
        - text: Tech articles
          link: /blog/second
